config/routes.rb
Rails.application.routes.draw do

  # Feed Management
  resources :feeds 

  # Entries Management
  get 'entries/index'
  get 'entries/show'

  # Homepage Management
  root 'entries#index'
  get '/about', to: 'static#about'
  get '/curation', to: 'static#curation'

  # User Management
  get '/signup', to: 'users#new'
  resources :users

  # Session Management
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Account Activation
  resources :account_activations, only: [:edit]

  # Password Resets
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  # Ratings Resources
  resources :ratings, only: [:new, :create, :edit, :update]

   # Feed Management
  resources :proposals

end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :user
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]

  def index
    proposals = Proposal.all
    list = labels
    total = User.all.count * 5.0
    if !proposals[0].nil?
      @deadline = proposals[0].created_at + 3.weeks
    else
      @deadline = Time.now + 3.weeks
    end
    @options = []
    list.each do |op|
      support = 0.0
      proposals.each do |pro|
        if op == pro.description
          support = support + User.find(pro.user_id).voting_power
        end
      end
      percent = ((support / total) * 100).round(2)
      @options.append([op, percent])
    end
  end

  def show
  end

  def new
    @proposal = Proposal.new
    @menu = labels
  end

  def edit
    @menu = labels
  end

  def create
    @proposal = Proposal.new(proposal_params)
    @proposal.user_id = current_user.id
    if @proposal.save
      flash[:success] = "Vote was successfully cast, "
      flash[:success] += "feel free to change before deadline"
    else
      flash[:warning] = "Vote was not correctly logged"
    end
    redirect_to proposals_path
  end

  def update
    if @proposal.update(proposal_params)
      flash[:success] = "Changes successfully made"
    else
      flash[:danger] = "Changes unable to be made"
    end
    redirect_to proposals_path
  end

  def destroy
    @proposal.destroy
    flash[:success] = "Proposal was axed"
  end

  private

  def set_proposal
    @proposal = Proposal.find(params[:id])
  end

  def labels
    list = ["Improve User Interface", "Improve Site Presence", 
            "Add More Feeds", "Improve User Experience", "None Of The Above"]
  end

  def proposal_params
    params.require(:proposal).permit(:description)
  end

end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.erb
<%= form_for(@proposal) do |f| %>
  <br>
  <%= f.select :description, @menu %>
  <br><br>
  <%= f.submit "Submit Vote", class: "btn btn-primary" %>
<% end %>

app/views/proposals/edit.html.erb
<h3>Change Vote</h3>
<div class="row">
  <div class="col-md-2">
    <%= render 'form' %>
  </div>
</div>

app/views/proposals/index.html.erb
<% if !current_user.nil? %>
  <h3>Current Proposals</h3>
  <br>
  <div class="listname"><p><strong>Proposal</strong></p></div>  
  <div class="votingpower"><p><strong>Voting</strong></p></div>
  <% @options.each do |op| %>
    <p>
      <div class="listname"><p><%= op[0] %></p></div>  
      <div class="votingpower"><p><%= op[1] %>%</p></div>
    </p>
  <% end %> 
  <br>
  <% if Time.now < @deadline %>
    <p>Time Left: <%= time_ago_in_words(@deadline) %></p>
    <% if current_user.proposal.nil? %>
      <p><%= link_to 'Vote Now', new_proposal_path %></p>
    <% else %>
      <p>
      <%= link_to 'Change Vote', edit_proposal_path(current_user.proposal) %>
      </p>
    <% end %>
  <% else %>
    <p>Voting Has Closed</p>
  <% end %>
<% else %>
  <p>Page Unavailable</p>
<% end %>

app/views/proposals/new.html.erb
<h3>Make Vote</h3>
<div class="row">
  <div class="col-md-2">
    <%= render 'form' %>
  </div>
</div>