config/routes.rb
Rails.application.routes.draw do

  # Feed Management
  resources :feeds 

  # Entries Management
  get 'entries/index'
  get 'entries/show'

  # Homepage Management
  root 'entries#index'
  get '/about', to: 'static#about'
  get '/curation', to: 'static#curation'

  # User Management
  get '/signup', to: 'users#new'
  resources :users

  # Session Management
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Account Activation
  resources :account_activations, only: [:edit]

  # Password Resets
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  # Ratings Resources
  resources :ratings, only: [:new, :create, :edit, :update]

   # Feed Management
  resources :proposals

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-left">
	<li><h3 id="title">newsiphy</h3></li>
      </ul>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
	<li id="header-item"><%= link_to "Home", root_path %></li>
	<li id="header-item"><%= link_to "About", about_path %></li>
        <% if logged_in? %>
	  <li id="header-item"><%= link_to "Users", users_path %></li>
	  <li id="header-item"><%= link_to "Proposals", proposals_path %></li>
	  <li id="header-item"><%= link_to "Edit Account", 
				   edit_user_path(current_user) %></li>
          <li id="header-item"><%= link_to "Logout", logout_path, 
				   method: :delete %></li>
          	  
        <% else %>
	  <li id="header-item"><%= link_to "Sign up", signup_path %></li>
	  <li id="header-item"><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>newsiphy</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 
	'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type%>"><%= msg %></div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>